services:
  haspro:
    image: haspro/${ENV}:latest
    container_name: haspro_${ENV}
    env_file: .env
    networks:
      - entrypoint
    volumes:
      - ./data/db:/app/data
      - ./data/media:/app/media
    restart: unless-stopped
    

networks:
  entrypoint:
    name: entrypoint
    external: true
